# Generated by Django 6.1.1 on 2026-09-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('national_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseClient',
            fields=[
                ('case_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_role', models.CharField(max_length=100)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100)),
                ('case_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('clients', models.ManyToManyField(through='core.CaseClient', to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='caseclient',
            name='case',
            field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='core.courtcase'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='core.courtcase')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='core.courtcase')),
                ('judge', models.ForeignKey(db_column='judge_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='core.courtcase')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='core.user')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='courtcase',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
