# Generated by Django 6.1.1 on 2026-09-16 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('role', models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='employee_profile',
            field=models.ForeignKey(db_column='employee_profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='receiver',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='core.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='core.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='judge',
            field=models.ForeignKey(db_column='judge_id', on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
