# Generated by Django 6.1.1 on 2026-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_notification_user_employeeprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='case_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='case_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
