# Generated by Django 6.1.1 on 2026-09-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courtcase_case_title_courtcase_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='case_subtype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
