# Generated by Django 6.1.1 on 2026-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courtcase_case_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
