# Generated by Django 6.1.1 on 2026-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_client_address_remove_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='defendant_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='plaintiff_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
