# Generated by Django 6.1.1 on 2026-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_defendant_email_client_plaintiff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='defendant_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='plaintiff_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
